version: '3.1'
services:
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "sibuser"
      POSTGRES_PASSWORD: "sibpassword"
      POSTGRES_DB: "sibaui"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
  influxdb:
    image: library/influxdb:1.1.1
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
    - influxdata:/var/lib/influxdb
    ports:
      - 8083:8083 # Web
      - 8086:8086 # TCP
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
volumes:
  postgres:
  influxdata: